
export const QUOTE_LIST_REQUEST = "QUOTE_LIST_REQUEST"
export const QUOTE_LIST_PROCESS = "QUOTE_LIST_PROCESS"

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST"
export const ORDER_LIST_PROCESS = "ORDER_LIST_PROCESS"
